language: java

sudo: false

dist: precise

jdk:
  - oraclejdk8

language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_OPTS="-Xmx2G"
    - MAVEN_OPTS="-Xmx2G"

before_script:
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS
  
script:
  - mvn test

after_success:
  - mvn coveralls:report -Ptravis